[workspace]
members = [
    "aurex-runtime",
    "aurex-kernel",
    "aurex-agent",
    "aurex-backend",
    "aurex-utils",
    "aurex-plugins/fpga_npu",
    "amduda"
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
