[package]
name = "aurex-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
aurex-kernel = { path = "../aurex-kernel" }
aurex-backend = { path = "../aurex-backend" }
async-trait = "0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
libloading = "0.8"
